apiVersion: apps/v1
kind: Deployment
metadata:
    name: ekglue
    annotations:
        "sidecar.jaegertracing.io/inject": "jaeger"
spec:
    replicas: 1
    template:
        spec:
            containers:
                - name: ekglue
                  image: ekglue
                  env:
                      - name: JAEGER_SERVICE_NAME
                        value: ekglue
                      - name: JAEGER_SAMPLER_TYPE
                        value: const
                      - name: JAEGER_SAMPLER_PARAM
                        value: "1"
                      - name: DEBUG_ADDRESS
                        value: "0.0.0.0:8081"
                      - name: MY_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: VERSION_PREFIX
                        value: "$(MY_POD_NAME)-"
                  readinessProbe:
                      grpc:
                          port: 9000
                      initialDelaySeconds: 1
                      periodSeconds: 10
                  livenessProbe:
                      grpc:
                          port: 9000
                      initialDelaySeconds: 10
                      periodSeconds: 10
                  ports:
                      - name: grpc
                        containerPort: 9000
                      - name: debug
                        containerPort: 8081
                  resources:
                      requests:
                          cpu: 10m
                          memory: 128Mi
                      limits:
                          memory: 128Mi
